### ISSUE TITLE
[UI,BE] Code cleanup - course related modules 

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/portal.ce.pdn.ac.lk#143]
Please check if there any residual code blocks (Specially JS codes) no longer in use and cleanup.

**Comment by NuwanJ** [comment]
@IsharaEkanayaka Please update this branch with the latest changes from `course-management-system`. I can see some functionalities not working after recent PR with I assume alpine change. Thanks!

**Comment by IsharaEkanayaka** [comment]
can you tell me the not working functionality so that it is easier to fix
it.
https://github.com/user-attachments/assets/a72500c3-706c-4e84-a873-d82a69e042bd
reason for this error is quill editor is not used for course/ semester
pages. Now i have removed quill initialization from app.blade.php . now
that error is not showing.

**Comment by NuwanJ** [comment]
My bad, I was in sleeping mode. Here is the issue I found:

![Image](https://github.com/user-attachments/assets/60cb77df-8338-4b9a-a663-7bbf3c2d5976)

Either the Next Button is not working or no Validation errors are shown. I can't go to the second page

**Comment by NuwanJ** [comment]
I merged the latest changes in course-management branch with this, so you can see it. It might be due to conflict of 2 PRs
